export const TIMEUPDATE_INTERVAL = 1000;
export const LENGTH_OF_DAYS = 7;
export const LENGTH_OF_MONTHS = 11;
export const LENGTH_DAY_CELLS = 42;
export const DEFAULT_LOCALE = 'en-US';
export const FIRST_DAY_OF_WEEK_DEFAULT: number = 1;
export const DEL_SHORT_DATE_SIGN = 3;
export const CELLS_CURRENT_MONTH_AND_YEARS_LENGTH = 12;
export const CELLS_MONTHS_AND_YEARS_LENGTH = 16;

export const FIRST_DAY_OF_WEEK_WITHOUT_MONDAY: Map<string, number> = new Map([
    ['af-ZA', 0],   // Afrikaans (South Africa)
    ['am-ET', 0],   // Amharic (Ethiopia)
    ['ar-AE', 6],   // Arabic (United Arab Emirates)
    ['ar-BH', 6],   // Arabic (Bahrain)
    ['ar-DZ', 6],   // Arabic (Algeria)
    ['ar-EG', 6],   // Arabic (Egypt)
    ['ar-IQ', 6],   // Arabic (Iraq)
    ['ar-JO', 6],   // Arabic (Jordan)
    ['ar-KW', 6],   // Arabic (Kuwait)
    ['ar-LB', 6],   // Arabic (Lebanon)
    ['ar-LY', 6],   // Arabic (Libya)
    ['ar-MA', 6],   // Arabic (Morocco)
    ['ar-OM', 6],   // Arabic (Oman)
    ['ar-QA', 6],   // Arabic (Qatar)
    ['ar-SA', 6],   // Arabic (Saudi Arabia)
    ['ar-SD', 6],   // Arabic (Sudan)
    ['ar-SY', 6],   // Arabic (Syria)
    ['ar-TN', 6],   // Arabic (Tunisia)
    ['ar-YE', 6],   // Arabic (Yemen)
    ['arn-CL', 0],  // Mapudungun (Chile)
    ['as-IN', 0],   // Assamese (India)
    ['bn-BD', 0],   // Bengali (Bangladesh)
    ['bn-IN', 0],   // Bengali (India)
    ['bo-CN', 0],   // Tibetan (China)
    ['dv-MV', 0],   // Divehi (Maldives)
    ['en-029', 0],  // English (Caribbean)
    ['en-AU', 0],   // English (Australia)
    ['en-BZ', 0],   // English (Belize)
    ['en-CA', 0],   // English (Canada)
    ['en-GB', 0],   // English (United Kingdom)
    ['en-IE', 0],   // English (Ireland)
    ['en-IN', 0],   // English (India)
    ['en-JM', 0],   // English (Jamaica)
    ['en-MY', 0],   // English (Malaysia)
    ['en-NZ', 0],   // English (New Zealand)
    ['en-PH', 0],   // English (Philippines)
    ['en-SG', 0],   // English (Singapore)
    ['en-TT', 0],   // English (Trinidad and Tobago)
    ['en-US', 0],   // English (United States)
    ['en-ZA', 0],   // English (South Africa)
    ['en-ZW', 0],   // English (Zimbabwe)
    ['fa-IR', 6],   // Persian (Iran)
    ['fil-PH', 0],  // Filipino (Philippines)
    ['gu-IN', 0],   // Gujarati (India)
    ['ha-Latn-NG', 0],   // Hausa (Latin, Nigeria)
    ['he-IL', 0],   // Hebrew (Israel)
    ['hi-IN', 0],   // Hindi (India)
    ['id-ID', 0],   // Indonesian (Indonesia)
    ['ig-NG', 0],   // Igbo (Nigeria)
    ['ii-CN', 0],   // Sichuan Yi (China)
    ['iu-Cans-CA', 0],   // Inuktitut (Syllabics, Canada)
    ['iu-Latn-CA', 0],   // Inuktitut (Latin, Canada)
    ['ja-JP', 0],   // Japanese (Japan)
    ['km-KH', 0],   // Khmer (Cambodia)
    ['kn-IN', 0],   // Kannada (India)
    ['kok-IN', 0],   // Konkani (India)
    ['ko-KR', 0],   // Korean (South Korea)
    ['lo-LA', 0],   // Lao (Lao PDR)
    ['ml-IN', 0],   // Malayalam (India)
    ['moh-CA', 0],  // Mohawk (Mohawk)
    ['mr-IN', 0],   // Marathi (India)
    ['ms-BN', 0],   // Malay (Brunei Darussalam)
    ['ms-MY', 0],   // Malay (Malaysia)
    ['ne-NP', 0],   // Nepali (Nepal)
    ['nso-ZA', 0],  // Sesotho sa Leboa (South Africa)
    ['or-IN', 0],   // Odia (India)
    ['pa-IN', 0],   // Punjabi (India)
    ['prs-AF', 6],   // Dari (Afghanistan)
    ['ps-AF', 6],   // Pashto (Afghanistan)
    ['qut-GT', 0],  // K'iche (Guatemala)
    ['sa-IN', 0],   // Sanskrit (India)
    ['si-LK', 0],   // Sinhala (Sri Lanka)
    ['sw-KE', 0],   // Kiswahili (Kenya)
    ['syr-SY', 6],   // Syriac (Syria)
    ['ta-IN', 0],   // Tamil (India)
    ['te-IN', 0],   // Telugu (India)
    ['th-TH', 0],   // Thai (Thailand)
    ['tn-ZA', 0],   // Setswana (South Africa)
    ['ug-CN', 0],   // Uighur (China)
    ['ur-PK', 0],   // Urdu (Islamic Republic of Pakistan)
    ['xh-ZA', 0],   // isiXhosa (South Africa)
    ['yo-NG', 0],   // Yoruba (Nigeria)
    ['zh-CN', 0],   // Chinese (Simplified, China)
    ['zh-HK', 0],   // Chinese (Traditional, Hong Kong SAR)
    ['zh-MO', 0],   // Chinese (Traditional, Macao SAR)
    ['zh-SG', 0],   // Chinese (Simplified, Singapore)
    ['zh-TW', 0],   // Chinese (Traditional, Taiwan)
    ['zu-ZA', 0],   // isiZulu (South Africa)
]);